// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PostFeed from "./PostFeed.bs.js";
import * as ReactDom from "react-dom";

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react mount element");
} else {
  ReactDom.render(React.createElement(PostFeed.make, {}), root);
}

if (import.meta.hot) {
  import.meta.hot.accept();
}

export {
  
}
/* root Not a pure module */
