// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Post from "./post.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.js";

function s(prim) {
  return prim;
}

function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* DeleteLater */0 :
        return {
                posts: state.posts,
                forDeletion: Belt_MapString.set(state.forDeletion, action._0.id, action._1)
              };
    case /* DeleteAbort */1 :
        return {
                posts: state.posts.concat([action._0]),
                forDeletion: state.forDeletion
              };
    case /* DeleteNow */2 :
        var post = action._0;
        return {
                posts: state.posts.filter(function (xpost) {
                      return xpost.id !== post.id;
                    }),
                forDeletion: state.forDeletion
              };
    
  }
}

var initialState = {
  posts: Post.examples,
  forDeletion: undefined
};

function newId(id, index) {
  return id + String(index);
}

function PostFeed$PostItem(Props) {
  var post = Props.post;
  var dispatch = Props.dispatch;
  var clearTimeOut = Props.clearTimeOut;
  var match = React.useState(function () {
        return false;
      });
  var setShowOptions = match[1];
  var toggleOptions = function (param) {
    var eventId = window.setTimeout((function (param) {
            return Curry._1(dispatch, {
                        TAG: /* DeleteNow */2,
                        _0: post
                      });
          }), 3000);
    console.log(eventId);
    Curry._1(dispatch, {
          TAG: /* DeleteLater */0,
          _0: post,
          _1: eventId
        });
    return Curry._1(setShowOptions, (function (param) {
                  return true;
                }));
  };
  var restoreButtonHandler = function (param) {
    Curry._1(clearTimeOut, post);
    return Curry._1(setShowOptions, (function (param) {
                  return false;
                }));
  };
  var deleteImmediately = function (param) {
    Curry._1(clearTimeOut, post);
    Curry._1(dispatch, {
          TAG: /* DeleteNow */2,
          _0: post
        });
    return Curry._1(setShowOptions, (function (param) {
                  return false;
                }));
  };
  if (match[0]) {
    return React.createElement("div", undefined, React.createElement("button", {
                    className: "bg-gray-300",
                    onClick: restoreButtonHandler
                  }, "Restore"), React.createElement("button", {
                    className: "bg-gray-300",
                    onClick: deleteImmediately
                  }, "Delete Immediately"));
  } else {
    return React.createElement("div", {
                className: "border border-gray-700"
              }, React.createElement("div", {
                    className: "text-xl font-bold"
                  }, post.title), React.createElement("div", {
                    className: "text-lg"
                  }, post.author), React.createElement("div", {
                    className: ""
                  }, Belt_Array.mapWithIndex(post.text, (function (index, para) {
                          return React.createElement("div", {
                                      key: post.id + String(index)
                                    }, para);
                        }))), React.createElement("button", {
                    className: "bg-gray-300",
                    onClick: toggleOptions
                  }, "Remove this post"));
  }
}

var PostItem = {
  make: PostFeed$PostItem
};

function PostFeed(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  var clearTimeOut = function (post) {
    Belt_Option.map(Belt_MapString.get(state.forDeletion, post.id), window.clearTimeout);
    
  };
  return React.createElement("div", {
              className: "max-w-3xl mx-auto mt-8 relative s"
            }, React.createElement("div", {
                  className: "space-y-5"
                }, Belt_Array.map(state.posts, (function (postData) {
                        return React.createElement(PostFeed$PostItem, {
                                    post: postData,
                                    dispatch: dispatch,
                                    clearTimeOut: clearTimeOut,
                                    key: postData.id
                                  });
                      }))));
}

var make = PostFeed;

export {
  s ,
  reducer ,
  initialState ,
  newId ,
  PostItem ,
  make ,
  
}
/* Post Not a pure module */
