// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Post from "./post.bs.js";
import * as React from "react";

function s(prim) {
  return prim;
}

function reducer(state, action) {
  return state;
}

var initialState = {
  posts: Post.examples,
  forDeletion: undefined
};

function PostFeed(Props) {
  React.useReducer(reducer, initialState);
  return React.createElement("div", {
              className: "max-w-3xl mx-auto mt-8 relative"
            }, React.createElement("p", undefined, "Container for posts!"));
}

var make = PostFeed;

export {
  s ,
  reducer ,
  initialState ,
  make ,
  
}
/* Post Not a pure module */
